POST https://rocket-node-do-zero.onrender.com/videos
Content-Type: application/json

{
    "title":"Video Teste",
    "description": "Primeiro vídeo",
    "duration": 100
}

###
GET https://rocket-node-do-zero.onrender.com/videos?search=node

###
GET https://rocket-node-do-zero.onrender.com/videos

###
PUT https://rocket-node-do-zero.onrender.com/videos/50401fcc-41ac-4a28-9e70-849b07c6e54f
Content-Type: application/json

{
    "title":"Alterado 01",
    "description": "Primeiro vídeo",
    "duration": 100
}

###
DELETE https://rocket-node-do-zero.onrender.com//videos/3c65d112-6b01-48f2-ad1a-920c950fbfa4